src/br/univali/ps/nucleo/PortugolStudio.java
src/br/univali/ps/ui/abas/AbaCodigoFonte.java

Resolvendo a issue #70 o cache das abas foi restaurado,
Não foi identificado erros com o depurador durante a restauração.
Se alguém tiver mais informações sobre o erro que dava no cache com o depurador peço para que me mandem mais informações, no momento parece estar tudo ok.

Restaurando Cache de Abas

---

build.xml

Criando novas funções para o builder do Portugol Studio
- Gerar Instalador
- Gerar Atualização

Atualizando Builder

---

src/br/univali/ps/ui/abas/BuscadorDeLinhasParaveis.java

Esse Pull Request complementa o Pull Request https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/66
Uma comparação também precisou ser feita no BuscadorDeLinhasPareaveis

Consertando bug do retorne em funções sem retorno.

---

src/br/univali/ps/ui/inspetor/RenderizadorDeMatriz.java
src/br/univali/ps/ui/inspetor/RenderizadorDeVetor.java

Esse pull request resolve a issue #86

Exibição da última coluna de vetores e matrizes

---

src/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java

- Decidimos permitir que o inspetor aceite tudo, incluindo contantes, maria mole, paçoca, e até mesmo o premiado café da lanchonete do Pedro, cujos grãos são macerados por freiras virgens do Himalaia em um ritual que dura 19 dias.
Não faz muito sentido inspecionar uma constante, mas a idéia é que o aluno per ceba isso e aprenda no processo. E se você pensar um pouco também não faz sentido tomar o café do Pedro. :)

Inspetor aceitando constantes

---

src/br/univali/ps/ui/FabricaDicasInterface.java
src/br/univali/ps/ui/WebConnectionUtils.java
src/br/univali/ps/ui/abas/AbaInicial.java
src/br/univali/ps/ui/telas/TelaLicencas.java
src/br/univali/ps/ui/telas/TelaSobre.java

- Abrindo os sites apartir de uma classe utilitária

Melhorando Sistema de links

---

src/br/univali/ps/nucleo/PortugolStudio.java
src/br/univali/ps/ui/abas/AbaCodigoFonte.form
src/br/univali/ps/ui/abas/AbaCodigoFonte.java
src/br/univali/ps/ui/editor/Editor.java
src/br/univali/ps/ui/rstautil/tree/AstOutlineTreeFactory.java
src/br/univali/ps/ui/rstautil/tree/PortugolOutlineTree.java
src/br/univali/ps/ui/rstautil/tree/SearchTextField.form
src/br/univali/ps/ui/rstautil/tree/SearchTextField.java
src/br/univali/ps/ui/rstautil/tree/filters/ASTFilter.java
src/br/univali/ps/ui/rstautil/tree/filters/CompoundFilter.java
src/br/univali/ps/ui/rstautil/tree/filters/DataTypeFilter.java
src/br/univali/ps/ui/rstautil/tree/filters/DataTypeFilterListener.java
src/br/univali/ps/ui/rstautil/tree/filters/PortugolASTFilter.java
src/br/univali/ps/ui/rstautil/tree/filters/PortugolASTFilterListener.java
src/br/univali/ps/ui/rstautil/tree/filters/SymbolNameFilter.java
src/br/univali/ps/ui/rstautil/tree/filters/SymbolNameFilterListener.java
src/br/univali/ps/ui/rstautil/tree/filters/SymbolTypeFilter.java
src/br/univali/ps/ui/rstautil/tree/filters/SymbolTypeFilterListener.java
src/br/univali/ps/ui/rstautil/tree/filters/view/DataTypeFilterView.form
src/br/univali/ps/ui/rstautil/tree/filters/view/DataTypeFilterView.java
src/br/univali/ps/ui/rstautil/tree/filters/view/SymbolTypeFilterView.form
src/br/univali/ps/ui/rstautil/tree/filters/view/SymbolTypeFilterView.java
src/br/univali/ps/ui/telas/TelaPrincipal.java
src/br/univali/ps/ui/weblaf/BarraDeBotoesExpansivel.java

Implementei o filtro por tipo de dados na árvore.
Por favor testem, mas não integrem ainda, vou acrescentar outros filtros antes de integrar.
O filtro está localizado no botão de configuração do editor, na AbaCodigoFonte.
Na pressa eu adicionei ali mesmo, depois vou mover pro local correto que é o botão de configuração da árvore.
Não esqueçam de fazer pull do master do Portugol-Nucleo, tem uma classe nova que eu adicionei.
Se você não fizerem pull, o código ficará quebrado.

Filtrando árvore por tipos de dado

---

src/br/univali/ps/ui/ColorController.java
src/br/univali/ps/ui/abas/AbaCodigoFonte.java
src/br/univali/ps/ui/editor/Editor.java
src/br/univali/ps/ui/editor/temas/dark.xml
src/br/univali/ps/ui/rstautil/tree/PortugolOutlineTree.java

Resolvendo bug nos cantos e adicionando novo esquema de cores

Novas cores

---

src/br/univali/ps/ui/inspetor/ItemDaLista.java
src/br/univali/ps/ui/inspetor/RenderizadorDeMatriz.java
src/br/univali/ps/ui/inspetor/RenderizadorDeVariavel.java
src/br/univali/ps/ui/inspetor/RenderizadorDeVetor.java

@AlissonSteffens e @AdsonEsteves , corrigi os problemas dos ícones no inspetor. Por favor testem essa branch antes de integrar no master.

Corrigindo ícones no inspetor

---

src/br/univali/ps/ui/abas/AbaCodigoFonte.form
src/br/univali/ps/ui/abas/AbaCodigoFonte.java
src/br/univali/ps/ui/abas/AbaConsole.java
src/br/univali/ps/ui/editor/Editor.form
src/br/univali/ps/ui/editor/Editor.java
src/br/univali/ps/ui/editor/EditorListener.java

Melhorando posicionamento dos ícones de configuração (engrenagens)

---

src/br/univali/ps/nucleo/Caminhos.java

Corrigindo caminho do javac no Linux (fix #193)

---

src/br/univali/ps/nucleo/PortugolStudio.java
src/br/univali/ps/ui/Lancador.java
src/br/univali/ps/ui/paineis/PainelExemplos.java
src/br/univali/ps/ui/window/BorderPanel.java
src/br/univali/ps/ui/window/OutsidePanel.java

Corrigindo o problema dos botões desaparecendo!
@AdsonEsteves , podes testar se os botões ainda estão desaparecendo? Aqui está funcionando corretamente. O problema principal era que o JFrame estava sendo criado fora da thread do Swing.

Corrigindo lancador (issue #212)

---

src/br/univali/ps/ui/abas/AbaCodigoFonte.java
src/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java
src/br/univali/ps/ui/rstautil/tree/PortugolOutlineTree.java

@AdsonEsteves , este PR corrige a issue #220. 
Para testar também é necessário fazer o pull da branch de mesmo nome (corrigindo-arvore) no repositório do núcleo.

Corrigindo geração da árvore quando vários arquivos são abertos (issue #220)

---

src/br/univali/ps/ui/abas/AbaCodigoFonte.java

@AdsonEsteves , esse PR corrige a issue #233.
Parece ser uma alteração bem simples, por isso estou desconfiado que não pode ser apenas isso e não comitei diretamente no master! 😄 
Podes testar situações que envolvam highlight para ver se está tudo ok? Os meus testes funcinaram ...
@noschang , por acaso você lembra porque colocamos essas linhas que o commit deste PR está removendo?

Corridingo destaque da linha quando executando com break points (fix #233)

---

src/br/univali/ps/nucleo/Configuracoes.java
src/br/univali/ps/ui/abas/AbaCodigoFonte.java
src/br/univali/ps/ui/abas/BotoesControleAba.java

Agora o diretório é memorizado também quando o usuário salva um aquivo novo, conforme o @rytix pediu. #263.

Salvando o último diretório aberto pelo usuário

---

CONTRIBUTING.md

[WIP] Create CONTRIBUTING.md

---

CODE_OF_CONDUCT.md

[WIP] Create CODE_OF_CONDUCT.md

---

src/br/univali/ps/ui/editor/PSTextArea.java

@elieserdejesus  Verifique se há algum problema pls :)
issue #273

Corrigindo pontos de parada sendo desativados em modificação no código (fix #273)

---

ide/src/main/assets/ajuda/recursos/exemplos/bibliotecas/exemplo2.por
ide/src/main/assets/ajuda/recursos/exemplos/declaracoes/funcao/exemplo2.por

Consertando exemplos da ajuda com problemas

---

ide/src/main/java/br/univali/ps/nucleo/Caminhos.java
ide/src/main/java/br/univali/ps/nucleo/Configuracoes.java

@AlissonSteffens e @AdsonEsteves , corrigi o caminho de instalação entretanto acho que existem outros erros nos caminhos que estão sendo definidos pelo instalador novo gerado pelo graddle.
Vocês conseguem continuar esse fix?

Corrigindo caminho de instalação

---

ide/src/main/java/br/univali/ps/ui/utils/FileHandle.java

Resolvendo parte da Issue #270

Verificando pasta antes de criar um arquivo

---

checker/src/main/java/br/univali/portugol/corretor/dinamico/Comparador.java
core/src/main/java/br/univali/portugol/nucleo/ErroAoRenomearSimbolo.java
core/src/main/java/br/univali/portugol/nucleo/RenomeadorDeSimbolos.java
ide/build.gradle
ide/src/main/java/br/univali/ps/nucleo/ExcecaoAplicacao.java
ide/src/main/java/br/univali/ps/nucleo/GerenciadorTemas.java
ide/src/main/java/br/univali/ps/nucleo/PortugolStudio.java
ide/src/main/java/br/univali/ps/nucleo/TratadorExcecoes.java
ide/src/main/java/br/univali/ps/ui/abas/AbaCodigoFonte.java
ide/src/main/java/br/univali/ps/ui/abas/abaAjuda/SwingBrowserHyperlinkHandler.java
ide/src/main/java/br/univali/ps/ui/paineis/PainelExemplos.java
ide/src/main/java/br/univali/ps/ui/telas/TelaPrincipal.java
ide/src/main/java/br/univali/ps/ui/telas/TelaRenomearSimbolo.java
ide/src/main/java/br/univali/ps/ui/utils/FileHandle.java
installer/build-configurations.json

Resolve issue #352 
Eventualmente o JOptionpane gerado pela exceção simples será trocado pelo QuestionPane do @AlissonSteffens

Separando exceções por erro de usuário e erro do programa

---

.gitattributes
installer/installers-project.xml

[WIP] Corrigindo o build no mac e linux

---

.travis.yml
core/src/test/java/br/univali/portugol/nucleo/bibliotecas/BibliotecaGraficosTest.java
ide/build.gradle
ide/src/main/java/br/univali/ps/ui/Lancador.java
ide/src/main/java/br/univali/ps/ui/abas/AbaCodigoFonte.java
ide/src/main/java/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java
ide/src/main/java/br/univali/ps/ui/telas/TelaPrincipal.java
ide/src/test/java/br/univali/ps/ui/IntegracaoAbaCodigoFonteTest.java

Pessoal, dei uma pesquisada em bibliotecas para testes funcionais com Swing e gostei da **AssertJ**. Nesse PR estou resolvendo a issue #350 e já aproveitei para escrever alguns testes que integram o editor, a árvore e o inspetor. 
Usando a **AssertJ** escrevi 4 testes que realmente abrem uma aba de código fonte e arrastam e soltam (programaticamente) variáveis para o inspetor. Depois verifico se o inspetor tem o número correto de variáveis, se não está duplicando variáveis, etc. Ou seja, com essa biblioteca de testes é possível simular interações complexas como Drag and Drop entre os componentes.  
Acho que vale a pena todos darem uma olhada nos commits que fiz nesse PR para ter uma ideia de como funciona e escrever testes desse tipo sempre que parecer útil. A biblioteca é fácil, bem …

Testes funcionais para o inspetor usando AssertJ

---

ide/src/main/java/br/univali/ps/nucleo/Configuracoes.java
ide/src/main/java/br/univali/ps/ui/abas/AbaCodigoFonte.java
ide/src/main/java/br/univali/ps/ui/abas/BotoesControleAba.java

Melhorando a função de salvar o último diretório aberto, agora permanecendo ao fechar o PS.
Testem aí.

:art: salvando último diretorio persistent

---

core/src/main/java/br/univali/portugol/nucleo/analise/semantica/AnalisadorSemantico.java
core/src/main/java/br/univali/portugol/nucleo/analise/semantica/erros/ErroAliasInexistente.java
core/src/main/java/br/univali/portugol/nucleo/analise/semantica/erros/ErroAtribuirFuncaoBiblioteca.java

:bug: corrigindo erros de atribuição em bibliotecas (fix #152)

---

core/src/main/java/br/univali/portugol/nucleo/analise/semantica/AnalisadorSemantico.java
core/src/main/java/br/univali/portugol/nucleo/analise/semantica/avisos/AvisoMatrizPodeSerVariavel.java
core/src/main/java/br/univali/portugol/nucleo/analise/semantica/avisos/AvisoMatrizPodeSerVetor.java
core/src/main/java/br/univali/portugol/nucleo/analise/semantica/avisos/AvisoVetorPodeSerVariavel.java

:gem: adicionando avisos caso os tamanhos de vetores ou matrizes sejam 1 (closes #276)

---

core/src/main/java/br/univali/portugol/nucleo/analise/semantica/AnalisadorSemantico.java
core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/GeradorCodigoJava.java
ide/src/main/java/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java

Corrigindo https://github.com/UNIVALI-LITE/Portugol-Studio/issues/498

:art: Inspetor exibindo variáveis globais no início da execução (close #498)

---

ide/src/main/java/br/univali/ps/ui/paineis/PainelExemplos.java

Enter: Abre Exemplo
SetaUP: Move seleção para cima
SetaDown: Move seleção para baixo

:gem: adicionado movimentação na busca de exemplos pelo teclado

---

console/src/main/java/br/univali/portugol/Console.java
core/src/main/java/br/univali/portugol/nucleo/analise/semantica/AnalisadorSemantico.java
core/src/main/java/br/univali/portugol/nucleo/asa/NoChamadaFuncao.java
core/src/main/java/br/univali/portugol/nucleo/asa/NoDeclaracaoFuncao.java
core/src/main/java/br/univali/portugol/nucleo/compilador/Compilador.java
core/src/main/java/br/univali/portugol/nucleo/execucao/ObservadorExecucao.java
core/src/main/java/br/univali/portugol/nucleo/execucao/ObservadorExecucaoBasico.java
core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/GeradorCodigoJava.java
core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/helpers/GeradorChamadaMetodo.java
core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/helpers/GeradorDeclaracaoMetodo.java
core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/helpers/GeradorLoops.java
core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/helpers/Utils.java
core/src/main/java/br/univali/portugol/nucleo/programa/Programa.java
core/src/test/java/br/univali/portugol/nucleo/execucao/GeradorCodigoTest.java
core/src/test/java/br/univali/portugol/nucleo/execucao/IntegracaoGeradorCodigoJavacTest.java
core/src/test/resources/br/univali/portugol/nucleo/execucao/arquivos/testSwitchComCasoContrario.javatest
core/src/test/resources/br/univali/portugol/nucleo/execucao/arquivos/testeGeracaoPontosDeParada.javatest
ide/src/main/java/br/univali/ps/ui/editor/Editor.java
ide/src/main/java/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java
ide/src/main/java/br/univali/ps/ui/inspetor/ItemDaLista.java
ide/src/main/java/br/univali/ps/ui/inspetor/ItemDaListaParaMatriz.java
ide/src/main/java/br/univali/ps/ui/inspetor/ItemDaListaParaVariavel.java
ide/src/main/java/br/univali/ps/ui/inspetor/ItemDaListaParaVetor.java
ide/src/main/java/br/univali/ps/ui/inspetor/RenderizadorBase.java
ide/src/main/java/br/univali/ps/ui/inspetor/RenderizadorDeMatriz.java
ide/src/main/java/br/univali/ps/ui/inspetor/RenderizadorDeVariavel.java
ide/src/main/java/br/univali/ps/ui/inspetor/RenderizadorDeVetor.java

**New feature**: inspetor "esmaecendo" as variáveis que estão fora de escopo durante a execução passo a passo:

:gem: Inspetor desabilitando variáveis fora de escopo durante execução passo a passo

---

docs/index.html

atual:
novo:
acho que deste jeito novo o botão de Download fica mais evidente

:art: alterando ordem dos menus

---

ide/src/main/java/br/univali/ps/ui/window/ComponentResizer.java

Desabilitando redimensionamento da janela quando maximizado (fix #594)

---

docs/assets/css/now-ui-kit.css
docs/index.html

:art:  arrumando posição de monitores flutuantes em celulares

---

installer/arquivos/linux/package/leia.txt

Foram utilizados globs para facilitar a instalação por parte do usuário.

:zap: Automatizando instruções de instalação

---

ide/src/main/assets/exemplos/bibliotecas/graficos/index.properties

Então, eu descobri que o nome disso é aparentemente Curvas de Lissajous, então mudei o nome do exemplo

atualizando nome do exemplo

---

ide/src/main/java/br/univali/ps/ui/Lancador.java

Monitores everywhere. 
Agora é possível maximizar em qualquer um dos monitores, independente da quantidade e posição do mesmo com relação ao principal.

Corrigindo monitores secundários

---

ide/src/main/java/br/univali/ps/ui/rstautil/completion/ProvedorConclusaoCodigoPrograma.java

Agora o auto complete também tem estruturas padrões como:
para
escreva
leia
escolha

:gem: adicionando estruturas padrões ao auto complete (closes #681)

---

ide/src/main/java/br/univali/ps/nucleo/TratadorExcecoes.java
ide/src/main/java/br/univali/ps/ui/abas/AbaCodigoFonte.java
ide/src/main/java/br/univali/ps/ui/utils/FileHandle.java

Basicamente tratando erros específicos que não podem ser resolvidos do lado do portugol como:
1 - Provedor OneDrive travando
2 - Arquivo sendo usado em outro processo
3 - Disco cheio

:bug: tratando erros não relacionados ao Portugol (fix #807) (fix #792)

---

core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/AnalisadorSintatico.java
core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/erros/ErroChaveDeVetorMatrizMalPosicionada.java
core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/erros/ErroRealComVirgula.java
core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/erros/ErroSimboloFaltandoOuRealComVirgula.java
core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/tradutores/TradutorMismatchedTokenException.java

No brainer esse.
Declarar um numero com virgulas ao invés de pontos.
Tentem achar outras possibilidades.
Valeria a pena fechar o #308 com esse, ou melhor deixar aberto ainda? Com certeza há outras mensagens de erro que não fazem sentido.

:bug: corrigindo mensagem de erro com reais com virgulas (fix #308)
