nbproject/project.properties, src/br/univali/ps/atualizador/GerenciadorAtualizacoes.java, src/br/univali/ps/nucleo/Mutex.java, src/br/univali/ps/nucleo/NamedThreadFactory.java, src/br/univali/ps/nucleo/PortugolStudio.java, src/br/univali/ps/ui/TelaPrincipal.java, src/br/univali/ps/ui/abas/AbaCodigoFonte.java, src/br/univali/ps/ui/rstautil/PortugolParser.java
@elieserdejesus. Por favor, teste e verifique se resolveu o problema do nome no MAC (issue #94). Aproveitei e alterei o projeto para dar nomes mais intuitivos às threads e assim facilitar a depuração usando o profiler.
Além disso, encontrei uma linha na tela de carregamento que referenciava o Java FX, talvez seja essa chamada que esteja bugando as outras partes da interface.
Vou abrir um pull request no núcleo também, pois alterei algumas coisas lá. Você deve fazer pull dos dois projetos para testar.
Se o nome alterar, me avise para que eu faça o merge.
=> Corrigindo issue #94

src/br/univali/ps/ui/abas/BuscadorDeLinhasParaveis.java
- O problema estava acontecendo porquem alguns nós da ASA não possuem uma
instância de TrechoCodigoFonte válida. Precisamos saber em que linha do código
o nó está, e quem sabe desta linha é o TrechoCodigoFonte. Quando o TrechoCodigoFonte retornava -1 como índice da linha a coisa toda bugava.
Apenas adicionei uma verificação para só considerar como nó parável aqueles
que possuem um índice de linha válido (maior ou igual a zero).
- Nos testes o bug do ponto de parada fantasma não apareceu mais. Entretanto
esse bug expõe uma coisa que poderíamos trabalhar futuramente. Por exemplo, atualmente é possível colocar um ponto de parada em uma declaração de variável,
mas não é possível fazer isso em uma declação de vetor. Why? Why? Whyyyy?
Simples! O nó da declaração de variável está retornando um …
=> Corrigindo o ponto de parada fantasma

src/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java, src/br/univali/ps/ui/inspetor/RenderizadorBase.java, src/br/univali/ps/ui/rstautil/ProcuradorDeDeclaracao.java
Este pull request corrige os bugs mencionados na issue #82 
@noschang , um dos problemas mencionados na issue estava relacionado com a criação das fontes usadas para desenhar as variáveis no inspetor. O código que criava essas fontes tinha sido comentado no construtor da classe **RenderizadorBase** e estava gerando exceções quando um vetor era arrastado para o inspetor. Eu lembro que tínhamos conversado sobre o problema de criar fontes que poderiam não estar disponíveis em algumas máquinas. Para resolver isso (fontes indisponíveis) eu tentei criar uma fonte padrão, que em teoria sempre estará disponível:
```
protected static Font FONTE_NORMAL = Font.decode(Font.SANS_SERIF + "-12");
```
Esse código cria uma fonte padrão sem serifa. Testei no Windows 10 aqui, **preciso da tua ajuda para …
=> Corrigindo bugs do inspetor

src/br/univali/ps/ui/inspetor/RenderizadorDeMatriz.java
Código para teste:
```
programa
{
funcao inicio()
{
const inteiro N = 10
inteiro matriz[N][5]
matriz[N-1][3] = 12
matriz[N-2][3] = 12
matriz[N-3][3] = 12
}
}
```
=> Corrigindo rolagem vertical da matriz fix #156

src/br/univali/ps/ui/inspetor/InspetorDeSimbolos.java, src/br/univali/ps/ui/inspetor/RenderizadorBase.java, src/br/univali/ps/ui/inspetor/RenderizadorDeMatriz.java, src/br/univali/ps/ui/inspetor/RenderizadorDeVariavel.java, src/br/univali/ps/ui/inspetor/RenderizadorDeVetor.java
- Aparentemente em algumas máquinas as fontes usadas no inspetor de variáveis não são criadas corretamente e isso acaba gerando NullPointerException quando um símbolo é arrastado para o inspetor.
=> Corrigindo fontes nulas no inspector de variáveis

src/br/univali/ps/ui/abas/AbaCodigoFonte.java
- Apenas setei a flag 'precisaRecompilar' no listener de "documentoModificado". Esse listener é invocado assim que a mudança no código é realizada. O código anterior setava essa mesma flag (precisaRecompilar) quando o listener do parser disparava. Esse listener do parser tem um delay, e se o usuário fosse mais rápido que esse delay (SHIFT + F6) o código antigo era executado.
=> Corrigindo o bug do programa anterior sendo executado (fix #206)

src/br/univali/ps/nucleo/Caminhos.java
@AdsonEsteves , esse PR corrige a issue #253. Testei bem rapidamente aqui, podes testar com mais calma? Acho que é impotrante testar "fora" do NetBeans. Podes gerar a versão multiplataforma para testar ou então substituir o Portugol-Studio.jar do instalador pelo arquivo modificado.
=> Corrigindo o erro nos forms que usavam a classe Caminhos (fix #253)

src/br/univali/ps/ui/rstautil/PortugolParser.java, src/logging.properties
O problema se dava pelo parser ser chamado quando o programa era finalizado (ou iniciado quando tinha o forceReparsing), e a analise ser pulada, assim passando pra frente resultados vazios.
=> Corrigindo problema dos avisos desaparecendo (fix #198)

core/src/main/java/br/univali/portugol/nucleo/RenomeadorDeSimbolos.java, core/src/main/java/br/univali/portugol/nucleo/analise/semantica/AnalisadorSemantico.java, core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/Portugol.g, core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/PortugolLexer.java, core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/PortugolParser.java, core/src/main/java/br/univali/portugol/nucleo/asa/NoPara.java, core/src/main/java/br/univali/portugol/nucleo/asa/VisitanteNulo.java, core/src/main/java/br/univali/portugol/nucleo/execucao/DetectaNosParada.java, core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/GeradorCodigoJava.java, core/src/main/java/br/univali/portugol/nucleo/execucao/gerador/helpers/GeradorDeclaracaoVariavel.java, core/src/test/java/br/univali/portugol/nucleo/analise/semantica/AnalisadorSemanticoTest.java, ide/src/main/java/br/univali/ps/ui/rstautil/ProcuradorDeDeclaracao.java, ide/src/main/java/br/univali/ps/ui/rstautil/completion/ProvedorConclusaoCodigoPrograma.java, ide/src/main/java/br/univali/ps/ui/rstautil/tree/AstOutlineTreeFactory.java
Este pull request resolve a issue #147. Agora é possível inicializar mais de uma variável no laço para.
Vejam na imagem mais abaixo.
A gramática estava bem defasada em relação ao codigo fonte. Então tive que fazer algumas alterações nela. É possível que as alterações da gramática tenham quebrado alguma coisa já que esta gramática é um buraco negro sem fim. Mas como os testes unitários passaram, só saberemos com o tempo.
Os testes unitários que eu rodei foram os que já existiam. O idela seria criar alguns testes unitários para testar esta minha nova implementação. Mas minha preguiça é maior do que minha força de vontade. 
Algum @elieserdejesus se habilita a escrever os testes? :grimacing: Please! Nunca te pedi nada. E você está me devendo um favor lembra? Kkkkkk
Segue abaixo algoritmo para …
=> Corrigindo inicializações do para

ide/src/main/java/br/univali/ps/nucleo/InstanciaPortugolStudio.java, ide/src/main/java/br/univali/ps/nucleo/Mutex.java, ide/src/main/java/br/univali/ps/nucleo/MutexImpl.java, ide/src/main/java/br/univali/ps/nucleo/PortugolStudio.java, ide/src/main/java/br/univali/ps/ui/Lancador.java
Grandes Mudanças:
*O Mutex foi movido da classe Portugol Studio para o Lancador.
*Em certas ocasiões o MutexImpl tentava acessar uma classe da thread do swing que ainda não existia, para evitar isso agora existe um flag no PortugolStudio que avisa quando ele terminou de carregar, e até o PS terminar de carregar o Socket fica aguardando em Loop.
=> Fix Issue #270

installer/jdk-minify-profile.json
Alguns arquivos da JDK haviam sido removidos durante a minimização. A falta destes arquivos fez com que algumas classes utilizadas na funcionalidade de reinicialização não fossem mais encontradas. Para resolver isso, configuramos o minimizador da JDK para manter estes arquivos.
**IMPORTANTE:** Após integrar este pull request, será necessário apagar as pastas do java no diretório de build do installer, para que o gradle baixe novamente o java e faça a minimização preservando estes arquivos.
=> :bug: Restaurando arquivos da JDK que impediam a reinicialização. Fix #385

console/src/main/java/br/univali/portugol/Console.java
Este pull request acrescenta um melhoria específica para o Linux.
Quando o programa é rodado via terminal do sistema operacional utilizando o comando ```portugol-console algoritmo.por```, se a função "limpa" for chamada no código, a tela do terminal é limpada de verdade. Antes isso não acontecia e os caracteres iam se acumulando na tela.
Algoritmo para testes:
```
programa
{
inclua biblioteca Util --> u
inclua biblioteca Tipos --> tp
inclua biblioteca Matematica --> mat
inclua biblioteca Texto --> txt
// Número de caracteres '=' que formam a barra. Desconsiderando as bordas formadas pelos caracteres '[' e ']'
// Você pode mudar o comprimento da barra à vontade que o resultado não será afetado.
// Escolhemos 78 caracteres porque o tamanho padrão dos consoles é 80, ou seja, 78 caracteres …
```
=> :gem: Limpando o console de verdade no Linux

ide/src/main/java/br/univali/ps/nucleo/Caminhos.java
Estou verificando agora se a pasta atual é compativel com o repositório, ao invés de verificar a pasta de instalação em cada plataforma.
Corrige #389 
Gerei instaladores com a modificação e estão no draft da 2.6.3
baixem, instalem e vejam se ocorreu algum problema nos caminhos (se os exemplos apareceram na aba inicial)
podem fazer isso ao abrir o portugol normalmente, abrir um .por, ou vários etc.
=> Corrigindo caminhos novamente (fix #389)

ide/src/main/java/br/univali/ps/ui/telas/TelaRenomearSimbolo.form, ide/src/main/java/br/univali/ps/ui/telas/TelaRenomearSimbolo.java
* Modificando ordem:
Em alguns textos dizem que faz mais sentido o botão de afirmação vir primeiro. [Link](https://ux.stackexchange.com/questions/1072/ok-cancel-on-left-right)
* Alterando cor ao sobrepor botões
Pics:
* Tema Dark:
Mouse sobre aceitar:
Mouse sobre cancelar:
* Tema Light:
Mouse sobre aceitar:
Mouse sobre cancelar:
=> :date: Modificando botões da tela renomear simbolo

ide/src/main/java/br/univali/ps/ui/rstautil/ProcuradorDeDeclaracao.java
Acontece ao mover uma referencia quando a declaração está no final do arquivo
Issue #496 
Testem para ver se não quebrou nada no inspetor
=> :bug: corrigindo arrastar variável ao inspetor (fix #496)

ide/src/main/java/br/univali/ps/ui/abas/AbaCodigoFonte.java
Quando há um erro de execução no meio da execução de um código, a aba saída é sempre trocada para a console.
=> :bug: trocando para aba console ao acontecer erro de execução (fix #580)

core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/erros/ErroExpressaoForaEscopoFuncao.java, core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/tradutores/TradutorMismatchedTokenException.java
Captura erros de expressões fora escopos de função. Como o da #883 .
Anteriormente retornava apenas que a variavel não tinha sido inicializada.
Agora com o #871 , ele consegue capturar como um token indesejavel e é possível dar uma melhor erro.
=> :bug: capturando erros de escopo

core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/tradutores/TradutorMismatchedTokenException.java
Na versão atual do master com o pull #884 aconteceu o problema de um dos testes falhar mas não ser pego pelo travis. (Por alguma razão estava desativado).
Fui verificar o problema e o portugol na versão do master, considera quealquer texto fora de um escopo, como um possível texto que pode ser colocado no escopo. ou seja, para ele um `escreva` fora de escopo tem a mesma validade que um `oijoij` jogado no meio do arquivo.
Nesse pull, o erro do escopo é removido, mantendo apenas o erro de "expressão inesperada". Que pede apenas que o texto seja removido.
Com o erro de fora de escopo, ele vai tratar as seguintes situações com o mesmo erro:
situação 1
situação 2
situacao 3
Sem ela, as três virariam esse erro:
Bom, existe a possibilidade de manter do jeito que está e só alterar o caso de …
=> removendo_erro_fora_de_escopo

core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/AnalisadorSintatico.java, core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/GeradorASA.java, core/src/main/java/br/univali/portugol/nucleo/analise/sintatica/erros/ErroPareForaDeLoopOuSwitch.java, core/src/test/java/br/univali/portugol/nucleo/analise/sintatica/erros/ErrosSintaticosTest.java
Essa issue (#761) foi resolvida jogando uma exceção de dentro do visitor.
Não é a melhor maneira de resolver, mas foi a mais fácil comparada à correta.
O problema do `pare` passa pelo fato de que ele pode ser apenas utilizado dentro de loops ou switchs, não importando o escopo local.
Isso deve ser resolvido no ANTLR, entretanto o nosso utiliza uma `listaDeComandos` que possui o `comando` contendo o `pare`. Essa lista é utilizada tanto nos loops, quanto no `se-senao`.
O problema começa quando `se` e `senao` só podem receber o comando `pare` se eles estiverem dentro de um loop. Até onde eu vi, com a atual gramática teria que se criar uma `se-senao` exclusivo para quando estão dentro do loop.
Isso escalaria em muitas modificações no visitor e códigos repetidos.
Se souberem de alguma outra …
=> :bug: corrigindo pare fora de loop switch (fix #761)

ide/src/main/assets/ajuda/recursos/exemplos/estruturas_controle/desvio/escolha_caso/exemplo1.por
Alguns estudantes estavam tentando fazer um escolha-caso de caracter usando aspas duplas, depois falavam que na documentação estava assim
=> :memo: Adicionando exemplo com carácter na ajuda
